.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 6/14/14               \" DATE 
.Dt trifi 1      \" Program name and manual section number
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm trifi,
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.Nm trificlient,
.Nm tr-fi
.\" Use .Nm macro to designate other names for the documented program.
.Nd program to upload WIFI signature profile to zappos whereis database.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl ep zxy              \" [-ep zxy]
.Op Fl ep Ar upload_endpoint         \" [-e upload_endpoint]
.Op Fl d               \" [-d]
.Op Fl h                \" [-h]
.Op Fl z Ar floor                \" [-z floor]
.Op Fl x Ar x_coord                \" [-x x_coord]
.Op Fl y Ar y_coord               \" [-y y_coord]
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
can be used to both report your current WIFI sig profile as well as train the machine learning database. 
use of the -z, -x, and -y params will switch the program into training mode instead of reporting mode
.Pp                      \" Inserts a space
A list of flags and their descriptions:
.Bl -tag -width -indent  \" Differs from above in tag removed 
.It Fl ep                 \"-a flag as a list item
endpoint to upload data to. 
.Ar http://tri-fi.zappos.biz/train
for training and 
.Ar http://tri-fi.zappos.biz/update
for reporting
.It Fl z
z coordinate as floor number. floors 1-10 (requires x and y as well)
.It Fl x
x coordinate on map grid (requires z and y as well)
.It Fl y
y coordinate on map grid (requires x and z as well)
.It Fl d
debug mode. will print out more detailed info about each access point including your current estimated distance
.It Fl h
prints out some help
.El                      \" Ends the list
.Pp
.\" .Sh ENVIRONMENT      \" May not be needed
.\" .Bl -tag -width "ENV_VAR_1" -indent \" ENV_VAR_1 is width of the string ENV_VAR_1
.\" .It Ev ENV_VAR_1
.\" Description of ENV_VAR_1
.\" .It Ev ENV_VAR_2
.\" Description of ENV_VAR_2
.\" .El                      
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "/Library/LaunchDaemon/com.zappos.trifi.plist" -compact
.It Pa /usr/bin/trifi
the trifi client program
.It Pa /Library/LaunchDaemon/com.zappos.trifi.plist
launchd profile to execute this program ever x secs (default to 30)
.El                      \" Ends the list
.\" .Sh DIAGNOSTICS       \" May not be needed
.\" .Bl -diag
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .El
.\" Sh SEE ALSO
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.\" Xr b 3
.\" .Sh BUGS              \" Document known, unremedied bugs 
.Sh HISTORY           \" Document history if command behaves in a unique manner
https://confluence.zappos.net/display/~bkirkby/Tri-Fi